### ISSUE TITLE
idea2018.2.3不行了，博主看下

### ISSUE THREAD

**Issue by kinsey-jian** [a252937166/idea-crack-jar#1]

**Comment by kinsey-jian** [comment]
要delete caches and settings ？ 我试试  我直接将之前的设置替换到当前的了

**Comment by kinsey-jian** [comment]
@a252937166  
![image](https://user-images.githubusercontent.com/30062085/45069872-41185f00-b101-11e8-971e-13dab73bd688.png) 还是不行  我哪里做的不对吗

**Comment by a252937166** [comment]
@kinsey-jian `key is invalid`应该是你的jar没配好，这个问题在3.1版本中明确提出有修复的，在2018.2.2能用不。
首先检查一下jar的版本，确认是`JetbrainsCrack-3.1-release-enc.jar`。
然后检查下`idea.vmoptions`（windows下是`idea.exe.vmoptions`和`idea64.exe.vmoptions`）里面`-javaagent:`的参数配置，建议写`JetbrainsCrack-3.1-release-enc.jar`的全路径。

如果3.1的jar包成功使用的话，code是可以乱填的，就算格式不对，会直接listened to rover12421

**Comment by kinsey-jian** [comment]
@a252937166 我解决了 原因是我在idea里面 写了 custom VM options 导致没有生效

**Comment by supremehover** [comment]
@a252937166 都是成都人，为啥你这么优秀！
